name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-haskell@v1
        with:
          stack-version: "2.7.3"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          # best effort for cache: tie it to Stack resolver and package config
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack

      - name: Install system dependencies
        run: |
          sudo apt-get install libsystemd-dev

      - name: Install dependencies
        run: |
          stack update
          stack build --only-dependencies
      - name: Build
        run: stack build
